name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # Specify your Node.js version
          registry-url: 'https://registry.npmjs.org'

      # 3. Install pnpm (this step is important)
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Install dependencies with pnpm (including semantic-release and plugins)
      - name: Install semantic-release and plugins with pnpm
        run: |
          pnpm install semantic-release @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      # 5. Run semantic-release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}        # npm token from GitHub Secrets
        run: pnpx semantic-release
