name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: read  # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write  # to be able to comment on released issues
      pull-requests: write  # to be able to comment on released pull requests
      id-token: write  # to enable use of OIDC for npm provenance

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 3. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      # 4. Install dependencies (including semantic-release plugins)
      - name: Install semantic-release and plugins
        run: |
          pnpm install semantic-release @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      # 5. Build your packages (if necessary)
      - name: Build packages
        run: pnpm run build:packages

      # 6. Run semantic-release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # npm token from GitHub Secrets
        run: pnpx semantic-release